package com.hawks.hawksbuziness.model.shops

import com.google.gson.annotations.SerializedName
import java.io.Serializable

data class ShopCustom(
    val address: String?,
    val auth_id: Int?,
    val branch: String?,
    val card: Any?,
    val category_id: Int?,
    val contact: String?,
    val country_id: Any?,
    val created: String?,
    val delete_status: Int?,
    val deleted_at: Any?,
    val deleted_by: Any?,
    val district_id: Any?,
    val domain: String?,
    val email: String?,
    val facebook: String?,
    val gstin: Any?,
    val id: Int?,
    val instagram: String?,
    val is_head_office: Int?,
    val is_multi_store: Int?,
    val is_pvt_ltd: Int?,
    val is_tm: Int?,
    val latitude: Any?,
    val linkedin: String?,
    val logo: String?,
    val longitude: Any?,
    val map_code: String?,
    val multi_store_id: Any?,
    val name: String?,
    val office_contact: String?,
    val pan_no: Any?,
    val payment_qr: Any?,
    val payment_qr_head: String?,
    val person_in_charge: String?,
    val place_id: Int?,
    val position: String?,
    val prime: Int?,
    val prime_card_type: String?,
    val prime_end_date: String?,
    val state_id: Any?,
    val status: Int?,
    val sub_category_id: Any?,
    val updated: String?,
    val website: Any?,
    val whatsapp: String?
): Serializable